### ISSUE TITLE
fonts are not inlined

### ISSUE THREAD

**Issue by du5t** [substack/html-inline#16]
example: 

```css
@font-face {
  font-family: 'fontin';
  src: url("fonts/Fontin-Regular.ttf");
}
```

becomes:

```html
<style>
@font-face {
  font-family: 'fontin';
  src: url("fonts/Fontin-Regular.ttf"); }
</style>
```

expected:
```html
<style>
@font-face {
  font-family: 'fontin';
  src:  url(data:font/ttf;base64,AAEA… ) format('truetype'); }
</style>
```
